FROM cloudsihmar/maven:spring AS build

WORKDIR /app

COPY . .

RUN mvn package


FROM openjdk:24-ea-17-jdk-oraclelinux8

COPY --from=build /app/target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar /run/petclinic.jar

EXPOSE 8080

CMD java -jar /run/petclinic.jar
